### ISSUE TITLE
returned non-zero exit status 24

### ISSUE THREAD

**Issue by TrollPirate** [Robbbbbbbbb/OpenEFT#11]
**Describe the bug**

Exception Value: | Command 'nfseg 13 1 1 1 0 /tmp/tmpwczo4zud/image.png' returned non-zero exit status 24.
-- | --
/usr/lib/python3.8/subprocess.py, line 516, in run

**Expected behavior**
Output of EFT file.

**Desktop (please complete the following information):**
 - OS: Windows/Docker

**Comment by Robbbbbbbbb** [comment]
This error indicates that there was an issue with the OCR of your fingerprint card. Make sure that the card is oriented correctly and that the OCR "Does this look correct?" train stop shows the correct fingerprint boxes.
