### ISSUE TITLE
Issues accessing outside 'localhost'

### ISSUE THREAD

**Issue by rtadams89** [Robbbbbbbbb/OpenEFT#2]
I see in the instructions you mention the possibility to access this from outside the local host. I've however run into 2 issues doing so. For clarity, I running this inside docker on Linux, but these issues would presumably exist when running docker on Windows as well.

First, the /root/OpenEFT/OpenEFT/settings.py file contains an empty array for "ALLOWED_HOSTS". This will block access to the site using any hostname/IP other than "localhost". You could change this to '*', but it may be a better idea to get this value from an environmental variable so that those running it in Docker can set it to any value they expect.

Second, the "Start New EFT" button on the main page is hardcoded to "localhost:8080/new". This should be updated to be a relative link so that it always works. It seems the links under File->New are already set this way so it should be done the same way.

**Comment by Robbbbbbbbb** [comment]
Fixed in 0.5.0 - thanks!
