### ISSUE TITLE
Existance of ".bak" files

### ISSUE THREAD

**Issue by rtadams89** [Robbbbbbbbb/OpenEFT#3]
There are a number of ".bak" files in the repository that are likely unneeded and should be deleted:

./templates/partials/navbar.bak
./templates/base.html.bak
./requirements.txt.bak
./openeft.bak
./conversion/templates/conversion/download.html.bak
./conversion/urls.py.bak
./conversion/core/fingerprint.py.bak
./conversion/core/fd258_ocr.py.bak
./conversion/core/fd258_ocr_10print.py.bak
./conversion/core/eft_helper.py.bak
./conversion/views.py.bak
./conversion/views.py.bak2
./about/urls.py.bak
./about/views.py.bak
./nbis/an2k/include/histogen.h.bak
./nbis/an2k/src/bin/histogen/chkfile.c.bak
./nbis/openjp2/src/lib/openjp2/src/bin/jp2/opj_compress.c.bak
./nbis/exports/include/histogen.h.bak
./build/include/histogen.h.bak

**Comment by Robbbbbbbbb** [comment]
Removed in 0.5.0 release.
