### ISSUE TITLE
Place of Birth Doesn't Support Non-US Countries

### ISSUE THREAD

**Issue by Robbbbbbbbb** [Robbbbbbbbb/OpenEFT#6]
Request to change POB so it supports non-U.S. countries

https://www.reddit.com/r/NFA/comments/1fsa6ot/comment/ls8lglj/

**Comment by freinkelhouse** [comment]
https://ucr.fbi.gov/fingerprints_biometrics/iafis/state_cntry2000.pdf
 has the full list. Easier to probably just make it free text

**Comment by Robbbbbbbbb** [comment]
EBTS format requires Place of Birth field be in ISO 3166-1 format (specifically, two-digit Alpha-2). I've added some logic in 0.5.0 to help with this. Released today!
