### ISSUE TITLE
.EFT File Size Too Large

### ISSUE THREAD

**Issue by astrotux** [Robbbbbbbbb/OpenEFT#8]
**Describe the bug**
EFT file size is greater than the 12mb max for Eforms

**Desktop (please complete the following information):**
Docker Image

**Additional context**
Adding the ability to compress the image files or control/preview the output size would be great.  I have tried both JPEG and PNG files ranging from 100-1200 dpi, and all produce .EFT files >13mb.

**Comment by Robbbbbbbbb** [comment]
Added some comments here in the download portion of the program, but this is typically due to poorly prepared prints or scans. Make sure there are no smudges or hard-pressed prints, and that there is no "dust" or weird artifacting in the white space of the FD-258.

**Comment by jblachly** [comment]
I'm having the same issue, with file sizes ranging from 15 MB to 80 MB no matter what I do. The prints on the card are of extremely high quality. I notice when examining in the viewer that the slaps have been upscaled to over 7000x3000 pixels (and similarly for the thumbs, but I don't remember their final size, although it was proportional)

**Comment by Robbbbbbbbb** [comment]
@jblachly - generally I see this a lot with "dusty" cards, or poorly transferred prints.

Examples of poorly transferred prints:

![Image](https://github.com/user-attachments/assets/6c5293c8-2927-4a2f-a562-8c1cd446e946)

Can you double-check your scan for me? Look for signs of dirt, dust, grain, or anything other than #FFFFFF for the background color. If you'd like me to troubleshoot the prints, you can email me the card -> Rob@PennArmory.com

**Comment by jblachly** [comment]
Thanks; none of the artifacts described or pictured appear present.

Beginning with a master scan at 600 dpi, I have tried (in Photoshop) downsampling all the way to 175 dpi (1400x1400 on an 8 inch card), compressing the levels to assure uniform white background and eliminate potentially too-dark areas (none were as pictured in the guidance image above), and combinations of the above.

When I examine the produced EFT file, I see that the 3x2 inch slaps are upscaled to ~2500 dpi.  This AFAICT is the only explanation for a < 1 MB PNG or JPG to blow up to a > 20 MB EFT.

I'll try to find a secure way to send some of my prints to you if I don't find any culprit in the codebase

**Comment by RCTMI** [comment]
I too see that the current version is creating a file size that is too big for e-forms. I tested with my prints on brand new clean FD cards. The original jpg I uploaded was at 600dpi with a file size of 4.57MB.
